name: CI

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./test.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.43.0/ktlint &&
          chmod a+x ktlint &&
          sudo mv ktlint /usr/local/bin/
      - run: ktlint --disabled_rules=filename
      - run: find -name *.rs -exec rustfmt \{\} \;
